sonar.projectKey=KhaledEl-Sman_url-shortener
sonar.organization=khaledel-sman
sonar.projectName=URL Shortener
sonar.projectVersion=0.1.0
sonar.sources=backend/src,frontend/js
sonar.tests=backend/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**
sonar.sourceEncoding=UTF-8
